services:
  racevision-db:
    image: postgres:16
    container_name: racevision-db
    restart: always
    environment:
      POSTGRES_DB: racevision
      POSTGRES_USER: racevision_user
      POSTGRES_PASSWORD: racevision_password
    ports:
      - "5432:5432"
    volumes:
      - racevision_postgres_data:/var/lib/postgresql/data

volumes:
  racevision_postgres_data: